### ISSUE TITLE
New features suggestion

### ISSUE THREAD

**Issue by GuildDio** [OAGuild/yuengine#1]
- Implement message filters to make chat experience more flexible. 
     This should solve two known problems: missing messages after map loading / level restart and separate
     log info from actual chat messages (right now it is hard to read when log info is mixed with chat).
 - Built-in translator for chat. Language to translate into and turning the translator ON/OFF are specified with
     new cvars. Auto-translate all the input messages (from all other users) and display to the user in a
     specified language (transliteration for sure).

*Sorry for being late!*

**Comment by The-Gig** [comment]
About the second one, can I say that sounds quite hard to achieve good results, considering the limitations automatic translators have (even if developed by Google) and the fact that gamers do probably mistype some words and use abbreviations due to haste?
Also, do you already know some GPLv2-compatible opensource translator engine (and dictionaries) which one may adapt?

**Comment by ryvnf** [comment]
The first suggestion has been implemented. :D Has filters for `sys` (log-info), `chat` (things written in all-chat), `tchat` (things written in team-chat) and `tell` (private messages). The console also interpret commands a bit differently. See the README for more information.

Don't think I will implement built-in translator. Not at this moment at least, but maybe some time in the future.

**Comment by ryvnf** [comment]
As the first item on this list has been implemented, and I don't have any intention of implementing the second item I will now close this issue.
