### ISSUE TITLE
EOF infinite loop on linux

### ISSUE THREAD

**Issue by psyych** [OAGuild/yuengine#5]
When compiled on manjaro, tty console gives me "EOF" printing loop. Cvars still work normally, you just can't read console message due to "EOF" spam. Loop disappeared once but once I closed session and logged in again, it was present.

**Comment by ryvnf** [comment]
Appears I accidentally left a `printf("EOF\n")` in an if-statement when attempting to understand how the tty-input works. Must have forgot to remove it as it never executed for me.

I manage to trigger the prints only when redirecting a file to stdin. And then it outputs EOF a couple of times. I cannot reproduce an infinite loop which prints EOF which I think is what you are describing.

Because it is possible to enter cvars and commands normally even when the console spams (which you wrote over email). Simply removing the print should solve the problem. The code surrounding the print comes from ioquake3, and I have problem understanding it (probably why I probably put the print statement there in the first place). So I think this should be good enough for now.

You can test the current master branch and see if the problem has gone away.
