### ISSUE TITLE
Shortcut keys and keyboard layout issue on Windows 7

### ISSUE THREAD

**Issue by psyych** [OAGuild/yuengine#6]
On W7, if using shortcut keys like CTRL or ALT for in-game commands like +movedown, it would cause other keys to lock and not work. Also not possible to type characters like '?' if using PT-BR kb layout, since it would trigger the delete last word shortcut (if on console) and type unicode blocks in on chat (all possible characters that you normally make by pressing alt + letter key would result in colored block)

**Comment by ryvnf** [comment]
Appears I accidentally left a `printf("EOF\n")` in an if-statement when attempting to understand how the tty-input works. Must have forgot to remove it as it never executed for me.

I manage to trigger the prints only when redirecting a file to stdin. And then it outputs EOF a couple of times. I cannot reproduce an infinite loop which prints EOF which I think is what you are describing.

Because it is possible to enter cvars and commands normally even when the console spams (which you wrote over email). Simply removing the print should solve the problem. The code surrounding the print comes from ioquake3, and I have problem understanding it (probably why I probably put the print statement there in the first place). So I think this should be good enough for now.

You can test the current master branch and see if the problem has gone away.

**Comment by ryvnf** [comment]
Looking back, the decision to use ALT to interpret commands in the console has caused some problems, as the interface is such that you cannot know each char-event is generated. Also that some ALT commands fail to register at all on windows (as described in #3).

Pressing `AltGr + 4` on a Swedish keyboard should output `$`, but in the current keyboard event handling used by the client, that is impossible to distinguish from `Alt + $`. I don't have as much time as I used to, so I can't rewrite the code to make it work as it should. This doesn't affect most keyboard layouts, but it probably affects many local ones.

The quick solution for now is to simply to not recognize the RALT key anymore. If someone comes across a better solution in the future, they are welcome to make a pull request.

Is `CTRL + W` used to trigger `?` on the PT-BR keyboard layout? It seems quite odd that it would use CTRL keys as a modifier. If that is the case unfortunately I don't think I can solve that issue. All characters pressed with the control modifier down are translated into ASCII control chars in the SDL wrapper.
